Kui 12
vladimirmagic/Kanbanchi-UI pull request #166
Opened 2020-08-17 19:55 UTC by andrey-lazarev

2020-08-25 04:58 UTC, AlexeyFominykh requested changes

2020-08-25 04:58 UTC, AlexeyFominykh commented on src/ui/icon/icon.tsx
> +            size = EIconSize.SIZE_24;
в задаче было не так:
если (size === 16) и (есть файл в папке 16)
или
если (size === 96) и (есть файл в папке 96)
то берём файл оттуда
в остальных случаях берём файл из папки 24

2020-08-25 04:58 UTC, AlexeyFominykh commented on stories/icons/utils.tsx
> +    let { xlink, size = EIconSize, title = '', key } = options;
size = объект?

2020-08-25 11:22 UTC, andrey-lazarev commented on stories/icons/utils.tsx
> +    let { xlink, size = EIconSize, title = '', key } = options;
enum

2020-08-27 11:41 UTC, andrey-lazarev commented on stories/icons/utils.tsx
> +    let { xlink, size = EIconSize, title = '', key } = options;
enum

2020-08-28 04:29 UTC, AlexeyFominykh commented on stories/icons/utils.tsx
> +    let { xlink, size = EIconSize, title = '', key } = options;
а enum это что?

2020-08-28 19:07 UTC, andrey-lazarev commented on stories/icons/utils.tsx
> +    let { xlink, size = EIconSize, title = '', key } = options;
я не понимаю сути вопроса

2020-08-30 19:31 UTC, andrey-lazarev commented on stories/icons/utils.tsx
> +    let { xlink, size = EIconSize, title = '', key } = options;
это было не нужно здесь, убрал

2020-09-01 05:32 UTC, AlexeyFominykh approved these changes

2020-09-01 05:43 UTC, merged