fix icons
vladimirmagic/Kanbanchi-UI pull request #167
Opened 2020-08-21 13:44 UTC by andrey-lazarev

2020-08-25 05:06 UTC, AlexeyFominykh requested changes

2020-08-25 05:06 UTC, AlexeyFominykh commented on stories/controls/files.tsx
> +                    <Button variant="icon"><Icon xlink="clear" size={24} /></Button>
trash = delete

2020-08-26 10:51 UTC, andrey-lazarev commented on src/ui/tooltip/tooltip.tsx
> +        // const icon = 'hint-arrow-' + arrow; //TODO no such icon in the new set
Done

2020-08-26 10:51 UTC, andrey-lazarev commented on stories/controls/files.tsx
> +                    <Button variant="icon"><Icon xlink="clear" size={24} /></Button>
Done

2020-08-27 11:40 UTC, merged